= Liste des tournois

L'objectif est de centraliser les informations des tournois proposés.

La liste des tournois est visible à l'adresse: https://sfauvel.github.io/slb/tournois[]

== Validation

Les données sont validées via l'action https://github.com/marketplace/actions/validate-json[].

Pour valider le fichier `json` localement, on peut executer le script `validate_against_schema.js`.

.To run validation
----
node validate_against_schema.js
----

// Pour valider le fichier `json` localement, on utilise un container docker: https://github.com/ISAITB/json-validator.
// ----
// docker run -d --name my-validator -p 8080:8080 \
//              -v /validator/resources:/validator/resources/ \
//              -e validator.resourceRoot=/validator/resources/  \
//              isaitb/json-validator

// ----

// jsonschema -i docs/tournois/tournois.json schema_tournois.json 

== Test

Pour visualiser le résultat localement, on peut démarrer un serveur http.

Cela peut se faire en démarrant un container docker depuis le répertoire contenant le fichier html (voir https://hub.docker.com/_/httpd[])

.Création du container du serveur http
----
docker run -dit -v $(pwd):/usr/local/apache2/htdocs --name my-running-app -p 8080:80 httpd:2.4
----


Pour démarrer le service http via devbox: `devbox services start apache`.
Le service est accessible sur : `http://localhost:8080/`

Le fichier `devbox.d/apache/httpd.conf` a été généré lors du démarrage du service.
Il a été modifié pour pointer vers le répertoire `docs/tournois`.

.Lancement du serveur http
----
docker start my-running-app
----

La page est alors visible à l'adresse: http://localhost:8080/[]