name: Validate JSONs

#on: [pull_request]

on:
  push:
    branches: [ data ]
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inspect
        run: |
          echo "ls"
          ls

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema_tournois.json
          INPUT_JSONS: ./docs/tournois/tournois.json

      - name: Inspect
        run: |
          echo "Le JSON est valide"

      - name: Configure Git user
        run: |
          git config user.email "actions@noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Merge from master
        run: git merge origin/pages -m "Mise à jour des données après validation"